openapi: 3.0.0
info:
  version: 1.0.0
  title: critterycovery API
servers:
  - url: 'https://critterycovery.me/api'
paths:
  /species:
    get:
      summary: 'Returns all species'
      responses:
        '200':
          description: JSON array of species names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
              example: 
                  [
                    {Alabama beach mouse: Peromyscus polionotus ammobates},
                    {American alligator: Alligator mississippiensis},
                    {Atlantic puffin: Fratercula arctica}
                  ]
  /species/{scientificName}:
    get:
      summary: 'Returns details about a particular species'
      operationId: getSpecies 
      tags:
          - species 
      parameters:
          - name: scientificName
            in: path
            description: Scientific name of the species
            required: true
            schema:
              type: string
      responses:
        '200':
          description: Species details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'
              example:
                scientificName: Peromyscus polionotus ammobates
                commonName: Alabama beach mouse
                stateID: AL
                habitat: Shrub & Herb Vegetation
                status: Listed
                rank: T1
                kingdom: Animalia
                phylum: Craniata
                taxclass: Mammalia
                taxorder: Rodentia
                family: Cricetidae
                genus: Peromyscus
  /habitat:
    get:
      summary: 'Returns all habitats'
      responses:
        '200':
          description: JSON array of habitat names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Habitat'
              example: 
                  [
                    {Shrub & Herb Vegetation: CLASS},
                    {Tropical Forest & Woodland: SUBCLASS},
                    {Desert & Semi-Desert: CLASS}
                  ]
  /habitat/{habitat}:
    get:
      summary: 'Returns details about a particular habitat'
      operationId: getHabitat
      tags:
          - habitat 
      parameters:
          - name: habitat
            in: path
            description: Habitat name
            required: true
            schema:
              type: string
      responses:
        '200':
          description: Habitat details 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Habitat'   
              example:
                scientificName: Tropical Forest & Woodland Subclass
                commonName: Tropical Forest & Woodland
                ecosystemType: SUBCLASS
                parentName: Forest & Woodland
                stateID: FL
                
  /countries:
    get:
      summary: 'Returns all countries'
      responses:
        '200':
          description: JSON array of country names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country' 
              example:
                {
                    "countries": [
                        {
                        "alpha2_code": "AF", 
                        "alpha3_code": "AFG", 
                        "area": 652230.0, 
                        "capital": "Kabul", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=Afghanistan", 
                        "flag": "https://restcountries.eu/data/afg.svg", 
                        "gini_index": 28, 
                        "latitude": 33.0, 
                        "longitude": 65.0, 
                        "name": "Afghanistan", 
                        "region": "Asia", 
                        "subregion": "Southern Asia", 
                        "total_pop": 27657145
                        }, 
                        {
                        "alpha2_code": "AX", 
                        "alpha3_code": "ALA", 
                        "area": 1580.0, 
                        "capital": "Mariehamn", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=\u00c5land Islands", 
                        "flag": "https://restcountries.eu/data/ala.svg", 
                        "gini_index": null, 
                        "latitude": 60.116667, 
                        "longitude": 19.9, 
                        "name": "\u00c5land Islands", 
                        "region": "Europe", 
                        "subregion": "Northern Europe", 
                        "total_pop": 28875
                        }, 
                        {
                        "alpha2_code": "AL", 
                        "alpha3_code": "ALB", 
                        "area": 28748.0, 
                        "capital": "Tirana", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=Albania", 
                        "flag": "https://restcountries.eu/data/alb.svg", 
                        "gini_index": 35, 
                        "latitude": 41.0, 
                        "longitude": 20.0, 
                        "name": "Albania", 
                        "region": "Europe", 
                        "subregion": "Southern Europe", 
                        "total_pop": 2886026
                        }
                    ]
                }

  /countries/name=<name>:
    get:
      summary: 'Search for a country by name'
      operationId: getCountry
      tags:
          - country 
      parameters:
          - name: name
            in: path
            description: Name of country
            required: true
            schema:
              type: string
      responses:
        '200':
          description: JSON object for a country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country' 
              example:
                  {
                    "country": {
                        "alpha2_code": "ES", 
                        "alpha3_code": "ESP", 
                        "area": 505992.0, 
                        "capital": "Madrid", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=Spain", 
                        "flag": "https://restcountries.eu/data/esp.svg", 
                        "gini_index": 35, 
                        "latitude": 40.0, 
                        "longitude": -4.0, 
                        "name": "Spain", 
                        "region": "Europe", 
                        "subregion": "Southern Europe", 
                        "total_pop": 46438422
                    }
                  }

  /countries/alpha2_code=<alpha2_code>:
    get:
      summary: 'Search for a country by ISO 2 code'
      operationId: getCountry
      tags:
          - country 
      parameters:
          - name: alpha2_code
            in: path
            description: ISO 2 of country
            required: true
            schema:
              type: string
      responses:
        '200':
          description: JSON object for a country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country' 
              example:
                  {
                    "country": {
                        "alpha2_code": "ES", 
                        "alpha3_code": "ESP", 
                        "area": 505992.0, 
                        "capital": "Madrid", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=Spain", 
                        "flag": "https://restcountries.eu/data/esp.svg", 
                        "gini_index": 35, 
                        "latitude": 40.0, 
                        "longitude": -4.0, 
                        "name": "Spain", 
                        "region": "Europe", 
                        "subregion": "Southern Europe", 
                        "total_pop": 46438422
                    }
                  }

  /countries/alpha3_code=<alpha3_code>:
    get:
      summary: 'Search for a country by ISO 3 code'
      operationId: getCountry
      tags:
          - country 
      parameters:
          - name: alpha3_code
            in: path
            description: ISO 3 of country
            required: true
            schema:
              type: string
      responses:
        '200':
          description: JSON object for a country
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country' 
              example:
                  {
                    "country": {
                        "alpha2_code": "ES", 
                        "alpha3_code": "ESP", 
                        "area": 505992.0, 
                        "capital": "Madrid", 
                        "embedded_map_link": "https://www.google.com/maps/embed/v1/place?key=AIzaSyBEA-sCsOy12Qca3i-jy2kF1nIRSulICNA&q=Spain", 
                        "flag": "https://restcountries.eu/data/esp.svg", 
                        "gini_index": 35, 
                        "latitude": 40.0, 
                        "longitude": -4.0, 
                        "name": "Spain", 
                        "region": "Europe", 
                        "subregion": "Southern Europe", 
                        "total_pop": 46438422
                    }
                  }

components:
  schemas:
    Habitat:
      type: object
      required:
        - name
      properties:
        id: 
            type: integer
        name: 
            type: string
        marine: 
            type: boolean
        reported_marine_area: 
            type: number
        reported_terrestrial_area: 
            type: number
        countries: 
            type: string
        iucn_category: 
            type: integer
        designation_name: 
            type: string
        designation_id: 
            type: integer
        link: 
            type: string
        image_link: 
            type: string
        embedded_map_link: 
            type: string
    Species:
      type: object
      required:
        - scientific_name
      properties:
        scientific_name: 
            type: string
        subspecies: 
            type: string
        kingdom: 
            type: string
        phylum: 
            type: string
        _class: 
            type: string
        _order: 
            type: string
        family: 
            type: string
        genus: 
            type: string
        common_name: 
            type: string
        population_trend: 
            type: string
        marine: 
            type: boolean
        freshwater: 
            type: boolean
        terrestrial: 
            type: boolean
        taxonomic_notes: 
            type: string
        rationale: 
            type: string
        geographic_range: 
            type: string
        population: 
            type: string
        text_habitat: 
            type: string
        threats: 
            type: string
        conservation_measures: 
            type: string
        image_link: 
            type: string
    Country:
      type: object
      required:
        - name
      properties:
        name: 
            type: string
        alpha2_code: 
            type: string
        alpha3_code: 
            type: string
        total_pop: 
            type: integer
        capital: 
            type: string
        region: 
            type: string
        subregion: 
            type: string
        latitude: 
            type: number
        longitude: 
            type: number
        area: 
            type: number
        gini_index: 
            type: integer
        flag: 
            type: string
        embedded_map_link: 
            type: string

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string